on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4.2.2

    - name: Set up Node.js
      uses: actions/setup-node@v4.1.0
      with:
        node-version: 'lts/*'
        check-latest: true

    - name: Install updated dependencies
      run: npm install

    - name: Compile TypeScript
      run: npm run build

    # Agregar un tag basado en el commit SHA o una convención que prefieras
    - name: Create a Git tag
      run: |
        TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
        git tag $TAG_NAME
        git push origin $TAG_NAME

    - name: Create Release and Upload Assets
      uses: softprops/action-gh-release@v2.1.0
      with:
        files: dist/index.js
