name: Build and Compile JavaScript and TypeScript

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Compile TypeScript
      run: npm run build

    - name: Run tests
      run: npm test

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: compiled-code
        path: ./dist
