on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code manually
      run: |
        git clone https://github.com/mazurikian/samfirm.js.git
        cd samfirm.js

    - name: Set up Node.js manually
      run: |
        curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
        sudo apt-get install -y nodejs
        node -v
        npm -v
        sudo apt install tree -y && tree

    - name: Install updated dependencies
      run: |
        npm install

    - name: Compile TypeScript
      run: |
        npm run build

    - name: Run Node.js script
      run: |
        node ./dist/index.js -r ARO -m SM-A236M -i 358263681238947

    - name: List directory contents
      run: |
        sudo apt install tree -y
        tree
