name: NodeJS with Grunt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    # Verifica el código desde el repositorio
    - uses: actions/checkout@v4

    # Configura Node.js en la versión especificada
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    # Instala las dependencias de npm y actualiza paquetes
    - name: Install and update dependencies
      run: |
        npm install
        npm update

    # Audita y corrige vulnerabilidades, si es necesario
    - name: Audit and fix vulnerabilities
      run: |
        npm audit fix || echo "Some vulnerabilities require manual review."

    # Ejecuta Grunt
    - name: Build with Grunt
      run: |
        grunt
